---
_test_vm_name: "{{ validation.test_vm.vm.market_name | d('Alpine Linux 3.21') }}"
# Vars for the test network
validation:
  test_vm:
    # Should we create a test network or reuse existing net? Existing network defined in {{validation.test_vm.vnet_name}} var
    create_vnet: true
    # Name of the virtual network to use (either existing or to be created)
    vnet_name: 'VLAN_580'
    vm:
      check_connection: true
      market_name: 'Alpine Linux 3.21'
      template_extra: |
        MEMORY="256"
        CONTEXT=[
          NETWORK="YES",
          REPORT_READY="YES",
          SSH_PUBLIC_KEY="$USER[SSH_PUBLIC_KEY]",
          TOKEN="YES" ]
    vnet:
      name: 'VLAN_580'
      desc: 'A test network for post-deployment cloud verification'
      bridge: 'br-test'
      vn_mad: 'dummy'
      phydev: 'eth1'
      network_address: '10.0.0.0'
      network_mask: '255.255.255.0'
      dns: '8.8.8.8'
      gateway: '10.0.0.254'
      ar:
        - type: "IP4"
          ip: '10.0.0.10'
          size: '10'

