---
# tasks file for OpenNebula cloud post-deployment verification

# Gather min subset of facts for datetime
- setup:
    gather_subset:
    - min

- name: Install ping dependencies
  ansible.builtin.package:
    name:
      - jc
      - jq
    state: present

- name: Populate service facts
  ansible.builtin.service_facts:

# !!! Might be reasonable to discuss alternative approach for this check
- name: Validate xml-rpc API
  ansible.builtin.shell: >
    oneuser list
  register: oneuser_result
  failed_when: "oneuser_result.rc != 0"

- name: Save xml-rpc status
  set_fact:
    verification_result: "{{ (verification_result | default({})) | combine({'XML-RPC API status': 'ok'}) }}"

- name: Check services enabled
  set_fact:
    verification_result: "{{ verification_result | combine({ item.desc + ' is enabled': 'ok'}) }}"
  when: ansible_facts['services'][ item.name ]['status'] | default('not-found') == 'enabled'
  with_items: "{{ validation.core_services.service_list }}"

- name: Check services restart
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: restarted
  register: restarted
  with_items: "{{ validation.core_services.service_list }}"

- name: Check services restarted
  set_fact:
    verification_result: "{{ verification_result | combine({ item.desc + ' restarted': 'ok'}) }}"
  when: ansible_facts['services'][ item.name ]['state'] | default('not-found') == 'running'
  with_items: "{{ validation.core_services.service_list }}"

- name: Check oned version
  ansible.builtin.shell: >
    oned -v  
  register: oned_version

- name: Save oned version
  set_fact:
    verification_result: "{{ verification_result | combine({'Oned version': oned_version.stdout}) }}"

- name: Printout oned version
  debug:
    msg: "Installed oned version: {{ oned_version.stdout }}"

- name: Extract version number from oned output
  set_fact:
    one_version: "{{ oned_version.stdout | regex_search('OpenNebula ([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') | first }}"

# Modify for Debian and RH-based distros        
- name: Verify OpenNebula private repos on the Debian-based OS
  ansible.builtin.shell: >
    grep -Ri opennebula /etc/apt/sources.list.d/ 2>/dev/null | head -1 | cut -d: -f1 | xargs cat | grep '^deb' | awk '{print $2}'
  register: debian_repos_list
  failed_when: false
  when: ansible_os_family == "Debian"

- name: Verify OpenNebula private repos on the RH-based OS
  ansible.builtin.shell: >
    grep -Ri opennebula /etc/yum.repos.d/*.repo 2>/dev/null | head -1 | cut -d: -f1 | xargs cat | grep baseurl | awk '{print $3}'
  register: rh_repos_list
  failed_when: false
  when: ansible_os_family == "RedHat"

- name: Save OpenNebula Debian repositories
  set_fact:
    verification_result: "{{ verification_result | combine({'Configured OpenNebula repository': debian_repos_list.stdout}) }}"
  when: debian_repos_list is defined and (debian_repos_list.skipped is not defined or not debian_repos_list.skipped)

- name: Save OpenNebula RedHat repositories
  set_fact:
    verification_result: "{{ verification_result | combine({'Configured OpenNebula repository': rh_repos_list.stdout}) }}"
  when: rh_repos_list is defined and (rh_repos_list.skipped is not defined or not rh_repos_list.skipped)

- block:
  - name: Verify OpenNebula scheduler can contact oned
    ansible.builtin.shell: |
      systemctl stop opennebula-scheduler && systemctl start opennebula-scheduler
      sleep 3
      grep 'oned successfully contacted' /var/log/one/sched.log
    register: one_scheduler
    failed_when: "one_scheduler.rc != 0"

  - name: Save OpenNebula scheduler can contact oned
    set_fact:
      verification_result: "{{ verification_result | combine({'OpenNebula scheduler can contact oned': 'ok'}) }}"
  when: one_version is version('6.99', '<')

- name: Verify one-gate listen & port on the server
  ansible.builtin.shell: >
    ss -tlpn | grep $(cat /etc/one/onegate-server.conf | awk '/^:port:/ {print $2}')
  register: onegate_service

- name: Save one-gate listen & port on the server
  set_fact:
    verification_result: "{{ verification_result | combine({'OpenNebula one-gate service listens on the server' : 'ok'}) }}"

- name: Save one-flow listen & port on the server
  set_fact:
    verification_result: "{{ verification_result | combine({'Verify one-flow stops and starts' : 'ok'}) }}"

- name: Verify oneflow listen & port on the server
  ansible.builtin.shell: >
    ss -tlpn | grep -o $(cat /etc/one/oneflow-server.conf | awk '/^:port:/ {print $2}')
  register: oneflow_status
  failed_when: "oneflow_status.rc != 0"
   
- name: Save one-flow listen & port on the server
  set_fact:
    verification_result: "{{ verification_result | combine({'Verify one-flow service port is open on the server' : 'ok'}) }}"

- block:
  - name: Verify fireedge GUI stops and starts
    ansible.builtin.shell: |
      systemctl stop opennebula-fireedge && systemctl start opennebula-fireedge
      sleep 3
      systemctl status opennebula-fireedge | grep Active | grep -o '(running)'
    register: fireedge_status
    failed_when: "'running' not in fireedge_status.stdout"

  - name: Verify fireedge GUI stops & starts
    set_fact:
      verification_result: "{{ verification_result | combine({'Verify fireedge GUI stops and starts' : 'ok'}) }}"

  - name: Verify fireedge service is configured to start at boot time
    ansible.builtin.shell: >
      systemctl status opennebula-fireedge | grep enabled
    register: fireedge_enabled
    failed_when: "'enabled' not in fireedge_enabled.stdout"

  - name: Verify fireedge GUI enabled
    set_fact:
      verification_result: "{{ verification_result | combine({'Verify fireedge GUI is enabled to start automatically' : 'ok'}) }}"

  - name: Fireedge service listens on the server
    ansible.builtin.shell: >
      ss -tlpn | grep $(cat /etc/one/fireedge-server.conf | awk '/^port:/ {print $2}')
    register: firedge_socket
    failed_when: "firedge_socket.rc != 0"
    retries: 5
    delay: 2
    until: firedge_socket.rc == 0

  - name: Verify fireedge GUI listens on the server
    set_fact:
      verification_result: "{{ verification_result | combine({'Verify fireedge GUI listens port' : 'ok'}) }}"

  - name: Connect to a fireedge server
    ansible.builtin.shell: >
      curl "{{ firedge_socket.stdout.split()[3] }}"
    register: connection_status
    failed_when: "connection_status.rc != 0"

  - name: Verify connection to a fireedge server
    set_fact:
      verification_result: "{{ verification_result | combine({'Verify connection to a fireedge server' : 'ok'}) }}"
  when: validation.core_services.check_fireedge_ui

- name: Get registered hosts
  ansible.builtin.shell: >
    onehost list -j
  register: onehost_list
  failed_when: "onehost_list.rc != 0"

- name: Get hosts list if there is only one host
  ignore_errors: true
  set_fact:
    single_host_list: "{{ onehost_list.stdout | from_json | json_query('HOST_POOL.HOST.{id: ID, hostname: NAME, state: STATE}') }}"
  failed_when: "onehost_list.rc != 0"

- name: Create host list with single host list
  when: single_host_list is mapping and single_host_list.hostname is defined and single_host_list.hostname is not none
  set_fact:
    hosts_list: [ "{{ single_host_list }}"]

- name: Get hosts list
  when: hosts_list is not defined
  set_fact:
    hosts_list: "{{ onehost_list.stdout | from_json | json_query('HOST_POOL.HOST[*].{id: ID, hostname: NAME, state: STATE}') | default([]) }}"
  failed_when: "onehost_list.rc != 0"

- name: Filter out empty entries from hosts list
  set_fact:
    hosts_list: "{{ hosts_list | select('mapping') | list }}"

- name: Verify hosts list
  set_fact:
    verification_result: "{{ verification_result | combine({'Status of the registered KVM hosts' : hosts_list if hosts_list | length > 0 else 'no hosts registered' }) }}"

- name: Set host offline and then set online
  ansible.builtin.shell: |
    onehost disable "{{ item.id }}"
    sleep 1
    onehost enable "{{ item.id }}"
    sleep 1
    onehost show "{{ item.id }}" -j
  register: host_monitoring
  loop: "{{ hosts_list }}"
  when: hosts_list | length > 0 

- name: Get host status
  debug:
    msg: "{{ host_monitoring }}"
  when: hosts_list | length > 0

# If we reached here all hosts monitoring is ok. Individual hosts status is in hosts_list variable    
- name: Verify host offline and then set online
  set_fact:
    verification_result: "{{ verification_result | combine({'Put hosts offline and then set online. Hosts status' : 'ok' if hosts_list | length > 0 else 'skipped - no hosts registered' }) }}"

- name: Get datastores list
  ansible.builtin.shell: >
    onedatastore list -j
  register: datastore_list
  failed_when: "datastore_list.rc != 0"

- name: Verify datastores list
  set_fact:
    verification_result: "{{ verification_result | combine({'Datastores list' : datastore_list.stdout | from_json | json_query('DATASTORE_POOL.DATASTORE[*].NAME')}) }}"

- name: Get DS capacity
  assert:
    that:
      - item['FREE_MB'] | int  >= 0
    quiet: true
    fail_msg: "{{item['NAME'] }} datastore  has no free space ({{ item['FREE_MB'] }}MB is available)"   
  when: "item['NAME'] != 'system'"  
  loop: "{{ datastore_list.stdout | from_json | json_query('DATASTORE_POOL.DATASTORE') }}"

- name: Verify DS capacity
  set_fact:
    verification_result: "{{ verification_result | combine({'Datastore capacity more than 0' : 'ok'}) }}"
  
  # We just checking how many marketplaces are registered, if no marketplaces -> fail
- name: Check marketplace
  ansible.builtin.shell: >
    onemarket list -j
  register: marketplace_list
  failed_when: marketplace_list.stdout | from_json | json_query('MARKETPLACE_POOL.MARKETPLACE') | length == 0

- name: Verify Marketplaces
  set_fact:
    verification_result: "{{ verification_result | combine({'Registered marketplaces' : marketplace_list.stdout | from_json | json_query('MARKETPLACE_POOL.MARKETPLACE[*].NAME')}) }}"

- name: Get marketplace status
  debug:
    msg: "{{ marketplace_list.stdout | from_json | json_query('MARKETPLACE_POOL.MARKETPLACE') | length }}"
